controller_frequency: 10

TrajectoryPlannerROS:
  max_vel_x: 0.5 #1.0
  min_vel_x: -1.0 #0.01 -  we want to set it to a large negative value because this enables the robotto back off when it needs to unstuck itself
  max_vel_theta: 1.0 #1.57

  min_in_place_vel_theta: 0.314

  acc_lim_theta: 3.14
  acc_lim_x: 2.0
  acc_lim_y: 2.0

  sim_time: 1.0

  vx_samples: 5.0
  vtheta_samples: 10.0

  pdist_scale: 0.6 #0.6
  gdist_scale: 0.8 #0.8
  occdist_scale: 0.02

  holonomic_robot: false

